[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
# `viaIR` flag needs to unabled since `Lightrelay.t.sol` requires it
viaIR = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@bob-collective/bitcoin-spv/=lib/bitcoin-spv/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]

